// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pedsmvjutwiwrjnqcymo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBlZHNtdmp1dHdpd3JqbnFjeW1vIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxNzgzMjIsImV4cCI6MjA2NDc1NDMyMn0.oKFRWcp7BdHq9RKtV9qGwywryoyD_pyf6y0zDry1aCw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);